### ISSUE TITLE
BelndMaxwell and Linux Mint Serena 18.1

### ISSUE THREAD

**Issue by Spirou4D** [uhlik/render_maxwell#13]
Hi uhlik,

I am Spirou4D, you remember me? I have re-installed my computer with the new Mint 18.1 Serena (Ubuntu Xenial 16.04) . My Maxwellrender 3.2.0.0 run correctly but your addon with an old Blender 2.77a (python 3.5) don't run. I have this traceback:
[CODE]
Traceback (most recent call last):
  File "/home/patrinux/.config/blender/2.77/scripts/addons/blendmaxwell/mxs.py", line 43, in <module>
    from pymaxwell import *
  File "/home/patrinux/Applications/Maxwell64-3.2/python/pymaxwell/python3.5/pymaxwell.py", line 26, in <module>
    _pymaxwell = swig_import_helper()
  File "/home/patrinux/Applications/Maxwell64-3.2/python/pymaxwell/python3.5/pymaxwell.py", line 22, in swig_import_helper
    _mod = imp.load_module('_pymaxwell', fp, pathname, description)
  File "/home/patrinux/Applications/blender-2.77a/2.77/python/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/patrinux/Applications/blender-2.77a/2.77/python/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libpython3.4m.so.1.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/patrinux/Applications/blender-2.77a/2.77/scripts/modules/addon_utils.py", line 330, in enable
    mod = __import__(module_name)
  File "/home/patrinux/.config/blender/2.77/scripts/addons/blendmaxwell/__init__.py", line 48, in <module>
    from . import system
  File "/home/patrinux/.config/blender/2.77/scripts/addons/blendmaxwell/system.py", line 30, in <module>
    from . import mxs
  File "/home/patrinux/.config/blender/2.77/scripts/addons/blendmaxwell/mxs.py", line 50, in <module>
    from pymaxwell import *
  File "/home/patrinux/Applications/Maxwell64-3.2/python/pymaxwell/python3.5/pymaxwell.py", line 26, in <module>
    _pymaxwell = swig_import_helper()
  File "/home/patrinux/Applications/Maxwell64-3.2/python/pymaxwell/python3.5/pymaxwell.py", line 22, in swig_import_helper
    _mod = imp.load_module('_pymaxwell', fp, pathname, description)
  File "/home/patrinux/Applications/blender-2.77a/2.77/python/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/patrinux/Applications/blender-2.77a/2.77/python/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libpython3.4m.so.1.0: cannot open shared object file: No such file or directory
[/CODE]

Because my Maxwell renderer 3.2.0.0 don't have pymaxwell for 3.5 and my pymaxwell has to be compiled with python3.4 because it ask libpython3.4m.so.1.0????

How Can I make, please. I am a little lost.
Thanks for your help, my Friend.
Spirou4D

EDIT: I tried with Blender 2.76a but i have the same traceback!!!!

**Comment by uhlik** [comment]
hi Spirou, is there any special reason you use maxwell 3.2.0.0? current version is 3.2.1.5 (as i remember) and current blendmaxwell works with maxwell 3.2.1.3+ and blender 2.77a+ only. please try last 3.x maxwell and last blender official release. from the error i read it tries to load pymaxwell from correct directory (ie Maxwell/../python3.5/..) but it can't load libpython of version 3.4 which is strange. maybe linux version of maxwell does not have updated pymaxwell for python 3.5 like others. i haven't tested linux version for a long time, only osx/win..

**Comment by Spirou4D** [comment]
Bu I can't update to 3.2.15. I must pay, not?
Yes libpython3.4m.so.i.0 don't exist on Mint Serena because python is 2.7 or 3.52 now.
Must I compile python3.4 in plus may be?
Thanks.

**Comment by uhlik** [comment]
there was no paid upgrade in 3.x series of maxwell, and i think compiling python won't solve anything since blender works with 3.5 which is included in blender installation, blender does not care about other python installations in system. go and download last 3.x maxwell, if it is still possible from customer section..

**Comment by uhlik** [comment]
hi Spirou, anything new on the issue?

**Comment by Spirou4D** [comment]
Hi Uhlik, 
Excuse me but Serena don't install the good driver for my sound card and I must to re-install all Serena after some try to compile the REALTEK driver. Serena use only the driver RT for ALC1200 and mine is ALC888S quadriphonie...
Now it's ok a new time and after re-install Maxwell Renderer and Blender 2.76+your addon 0.45: all is ok too! I don't understand but all run! 
May be Serena has to be updated....

Thanks for your interest and congrats for your add-on very useful for me. Like you this release is sufficient for me. I will try your addon with Blender 2.77a to see. But I am happy with that!
Byebye
Patrick D.

**Comment by uhlik** [comment]
glad it is working
