### ISSUE TITLE
Exception in the addon

### ISSUE THREAD

**Issue by Sniperbeer** [uhlik/render_maxwell#14]
Hi,
When I try to activate the addon I get this error.
I'm using Blender 2.7.8a on windows 10 64bits.

```Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.78\scripts\modules\addon_utils.py", line 330, in enable
    mod = __import__(module_name)
  File "C:\Users\Redacted\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\blendmaxwell\__init__.py", line 48, in <module>
    from . import system
  File "C:\Users\Redacted\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\blendmaxwell\system.py", line 30, in <module>
    from . import mxs
  File "C:\Users\Redacted\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\blendmaxwell\mxs.py", line 56, in <module>
    pp = os.path.abspath(os.path.join(mp, 'python', 'pymaxwell', 'python3.5'))
  File "C:\Program Files\Blender Foundation\Blender\2.78\python\lib\ntpath.py", line 113, in join
    genericpath._check_arg_types('join', path, *paths)
  File "C:\Program Files\Blender Foundation\Blender\2.78\python\lib\genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'

`

**Comment by uhlik** [comment]
hi, looks like you don't have maxwell installed or missing MAXWELL3_ROOT environment variable (created by maxwell installer). would you verify you have latest maxwell 3 installed? addon does not work with maxwell 2.x and 4.x, and version 3.x must be 3.2.1.3 and later.
