### ISSUE TITLE
Exception on Blender 2.77

### ISSUE THREAD

**Issue by nbgo** [uhlik/render_maxwell#9]
Hello. I try to activate this addon on Blender 2.77 and see this:

```
Traceback (most recent call last):
  File "C:\Users\Nikolay\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\blendmaxwell\mxs.py", line 53, in <module>
    from pymaxwell import *
ImportError: No module named 'pymaxwell'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "I:\Dropbox\Progs\blender\2.77\scripts\modules\addon_utils.py", line 330, in enable
    mod = __import__(module_name)
  File "C:\Users\Nikolay\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\blendmaxwell\__init__.py", line 48, in <module>
    from . import system
  File "C:\Users\Nikolay\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\blendmaxwell\system.py", line 30, in <module>
    from . import mxs
  File "C:\Users\Nikolay\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\blendmaxwell\mxs.py", line 61, in <module>
    from pymaxwell import *
  File "C:\Program Files\Next Limit\Maxwell 3\python\pymaxwell\python3.4\pymaxwell.py", line 30, in <module>
    _pymaxwell = swig_import_helper()
  File "C:\Program Files\Next Limit\Maxwell 3\python\pymaxwell\python3.4\pymaxwell.py", line 26, in swig_import_helper
    _mod = imp.load_module('_pymaxwell', fp, pathname, description)
  File "I:\Dropbox\Progs\blender\2.77\python\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "I:\Dropbox\Progs\blender\2.77\python\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: Module use of python34.dll conflicts with this version of Python.
```

**Comment by uhlik** [comment]
hi, it looks like you are trying to activate current master (which is for blender 2.76) in blender 2.77. this will not work because it uses pymaxwell for python 3.4 while blender 2.77 uses python 3.5. try "py3.5" branch here https://github.com/uhlik/blendmaxwell/tree/py3.5

**Comment by nbgo** [comment]
Thank you. Perfect.
